name: tags only master
on:
  release:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v1
      - name: Echo test
        run: echo 'tags-only-master'
      - name: Print variables
        run: |
          echo ${{ github.ref }}
