name: tags only master
on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v1
      - name: Print git branch
        run: |
          git branch
      - name: Print variables
        run: |
          echo ${{ github.ref }}
