name: Get branch name from tags
on:
  push:
    tags:
      - '*'
    branches-ignore:
      - '!master'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v1
